name: Build Windows Executables

on:
  push:
    branches:
      - main  # 推送到 main 分支时触发
  pull_request:  # 拉取请求时触发
    branches:
      - main

jobs:
  build:
    name: Compile for Windows
    runs-on: windows-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 安装 MinGW
      - name: Install MinGW
        run: |
          choco install mingw -y
        shell: cmd

      # 添加 MinGW 的路径到环境变量
      - name: Add MinGW to PATH
        run: |
          echo "C:\tools\mingw64\bin" >> $env:GITHUB_PATH
        shell: pwsh

      # 编译 32 位版本
      - name: Compile 32-bit EXE
        run: |
          gcc -m32 -o write_mbr_32.exe write_mbr.c

      # 编译 64 位版本
      - name: Compile 64-bit EXE
        run: |
          gcc -m64 -o write_mbr_64.exe write_mbr.c

      # 上传生成的文件作为工件
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-executables
          path: |
            write_mbr_32.exe
            write_mbr_64.exe
